import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import VideoHero from '../components/VideoHero'
import Categories from '../components/Categories'
import Card from '../components/Card'
import ImageText from '../components/ImageText'

import HeroHome from '../public/hero_home.jpg'
import One from '../public/1.jpg'
import Two from '../public/2.jpg'
import Three from '../public/3.jpg'
import Maria from '../public/4.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Marias Rum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VideoHero
        title='Marias Rum er et kropsterapeutisk univers'
        buttonText='Kontakt mig i dag'
      />
      <Categories title='Hvad jeg tilbyder'>
        <Card
          src={One}
          smallTitle='Kropsterapi'
          bigTitle=''
          text='Behandling af stress, dybe traumer og sorg gennem kropsterapeutiske forløb'
          buttonText='Læs mere'
          href='/'
        />
        <Card
          src={Two}
          smallTitle='Det Kærlige Brusebad'
          bigTitle=''
          text='Opdag dine sande styrker og talenter gennem mit koncept, Det Kærlige Brusebad'
          buttonText='Læs mere'
          href='/'
        />
        <Card
          src={Three}
          smallTitle='ManuVision træning'
          bigTitle=''
          text='ManuVision træning forbedrer din energi og kropsholdning, så der bliver mere plads til glæde og nysgerrighed'
          buttonText='Læs mere'
          href='/'
        />
      </Categories>
      <ImageText
        src={Maria}
        title='Hvem er Maria?'
        text='Jeg er uddannet kropsterapeut, og kan hjælpe dig med at bearbejde din stress, sorg og traumer gennem kropsterapeutiske forløb, og kan desuden hjælpe dig med styrke din krop og sind gennem ManuVision-træning og mit eget terapeutiske koncept, Det Kærlige Brusebad. Dyk ned i mine forløb eller artikler her på siden'
        layout='right'
        href='/om-marias-rum'
      />
    </>
  )
}
